const STORAGE_KEY = 'naomiPromptDirector.v2';

const packRows = [
['Moody hotel satin','seductive-luxury','wearing a form-fitting black satin off-shoulder mini dress with long sheer sleeves, sculpted sweetheart neckline, cinched waist, upper-thigh hem, sheer black tights, gold jewelry, black stiletto heels, elegant seductive evening styling','in a moody luxury boutique hotel suite at night with cream plaster walls, dark walnut furniture, linen curtains, velvet lounge chair, brass accents, deep shadows, muted black beige and gold palette','soft warm low evening lamp light, realistic shadow shaping across face and body, sharp focus, subtle grain, warm neutral black beige and gold color grade'],
['High-rise burgundy','seductive-luxury','wearing a fitted deep burgundy bodycon mini dress with square neckline, long sleeves, smooth stretch fabric, sheer black tights, gold necklace, black pointed heels','in a modern high-rise apartment at night with floor-to-ceiling windows, city lights, warm interior lamps, walnut furniture, cream walls, dark glass reflections','mixed cool city-window and warm interior lamp light, sharp focus, subtle grain, cinematic high-rise evening color grade'],
['Black leather lounge','bold-nightlife','wearing a black fitted bodysuit with high-waisted black leather mini skirt, sheer black tights, gold jewelry, black pointed heels, sleek confident evening styling','in a moody cocktail lounge corner with dark velvet seating, brass tables, amber wall sconces, black marble accents, deep shadows, refined nightlife atmosphere','warm amber wall-sconce lighting, soft directional shadows, sharp subject focus, subtle grain, deep black burgundy and gold grade'],
['Dressing room blazer','fashion-editorial','wearing a fitted black satin slip-style mini dress under a cropped tailored black blazer, sheer black tights, gold jewelry, black pointed heels','in an upscale walk-in wardrobe with vanity lights, dark wood shelving, hanging neutral clothes, full-length mirror, brass hardware, soft carpet','soft warm vanity mirror lighting, flattering even glow, sharp fabric detail, subtle grain, polished natural evening finish'],
['Balcony sweater dress','soft-seductive','wearing a charcoal grey off-shoulder fitted sweater dress with long sleeves, sculpted waist, sheer black tights, small gold hoops, black heels','on a private high-rise balcony at night with city lights, warm indoor light through glass doors, dark railing, curtains behind her, blue-and-gold atmosphere','cool city-night ambience mixed with warm indoor spill light, realistic shadows, subtle grain, cinematic blue-and-gold grade'],
['Beach sunset swim','summer-sultry','wearing a tasteful black high-waisted bikini with structured bandeau top, open oversized white linen shirt as cover-up, gold anklet, small hoops, barefoot beach styling','on a quiet sandy beach near shoreline with soft waves, pale sand, distant rocks, minimal beach bag, open sky and ocean horizon','golden-hour sunset light, warm low side sun, soft rim light, natural skin texture, subtle grain, peach and gold color grade'],
['Poolside resort','summer-sultry','wearing a sleek dark espresso one-piece swimsuit with low square neckline, high-cut leg, thin gold chain belt detail, linen shirt draped from shoulders, resort styling','beside a quiet luxury resort pool with pale stone deck, cream loungers, folded towels, potted palms, blue water reflections','bright warm late-afternoon sun softened by shade, crisp realistic shadows, sharp focus, clean resort lifestyle color grade'],
['Rooftop ivory dress','summer-sultry','wearing a fitted ivory ribbed knit mini dress with deep square neckline, thin straps, sculpted waist, gold jewelry, nude strappy heels','on a private rooftop terrace with low cream seating, planters, glass railing, city skyline, minimal luxury decor','warm golden-hour rooftop light, soft side illumination, subtle grain, cream and gold premium lifestyle grade'],
['Modern kitchen bodysuit','candid-lifestyle','wearing a fitted black long-sleeve bodysuit tucked into high-waisted cream tailored trousers, slim black belt, gold necklace, black heels','in a sleek modern condo kitchen at night with dark stone island, warm pendant lights, walnut cabinets, cream walls, minimal luxury decor','warm pendant light from above and slightly forward, realistic shadow falloff, sharp fabric detail, subtle grain, muted condo color grade'],
['Rainy window cozy','soft-seductive','wearing an oversized cream off-shoulder knit sweater slipping at one shoulder, fitted black micro shorts mostly covered by sweater hem, bare legs, gold necklace','in a cozy modern apartment beside a rain-streaked window, soft sofa, throw blanket, walnut side table, warm lamp glow, blurred city rain outside','soft warm lamp light mixed with cool rainy window reflections, gentle contrast, subtle grain, cozy blue-and-amber grade'],
['Garden patio linen','fresh-lifestyle','wearing a fitted black linen corset-style top with high-waisted cream linen shorts, gold jewelry, leather sandals, effortless summer styling','on a private garden patio with stone pavers, olive trees, cream cushions, rattan chair, wood table, neutral ceramics, soft greenery','soft late-morning diffused sunlight through greenery, dappled shadows, sharp focus, warm cream green and tan grade'],
['Gym mirror set','fitness-lifestyle','wearing a fitted dark charcoal matching workout set with cropped square-neck athletic top, high-waisted contour leggings, white socks, black trainers','in a private luxury apartment gym with dark rubber flooring, full-length mirrors, matte black weights, walnut accent wall, towel bench','clean soft overhead gym lighting with subtle side fill, sharp focus, neutral black grey and warm wood grade'],
['Yacht white swim','summer-sultry','wearing a tasteful white textured one-piece swimsuit with low square neckline, open white linen shirt tied at waist, gold anklet, small hoops, sunglasses','on a private yacht deck near a marina with polished white fiberglass, teak flooring, cream cushions, chrome railings, calm blue water, distant boats','bright clean marina sunlight softened by sea haze, crisp shadows, sharp focus, blue white and gold summer grade'],
['Spa terrace robe','soft-seductive','wearing a soft ivory belted spa robe draped off one shoulder over a fitted cream ribbed tank dress, bare legs, gold necklace, sandals','on a quiet luxury spa terrace with pale stone floor, linen loungers, low greenery, rolled towels, ceramic planters, privacy screens','soft morning resort light, airy neutral grade, gentle warm shadows, realistic skin texture, clean calm photo finish'],
['After-hours office','fashion-editorial','wearing a fitted black sleeveless turtleneck tucked into high-waisted charcoal pencil skirt, sheer black tights, black pointed heels, slim gold watch','in a modern executive office after dark with glass walls, walnut desk, leather chair, city lights outside, dim desk lamp, black and brass decor','low warm desk-lamp light mixed with cool city reflections, directional shadows, subtle grain, polished cinematic office grade'],
['Elevator lobby emerald','bold-nightlife','wearing a fitted emerald satin mini dress with thin straps, sculpted waist, sheer black tights, black strappy heels, delicate gold earrings','in an upscale hotel elevator lobby with brass elevator doors, cream paneled walls, dark patterned carpet, warm wall sconces, black marble side table','warm sconce and elevator-lobby lighting, soft highlights, deeper shadows, emerald black and brass evening grade'],
['City street leather coat','bold-nightlife','wearing a fitted black mini dress under a long black leather trench coat worn open, sheer black tights, black ankle boots, gold hoops','on a quiet upscale city street at night with wet pavement reflections, dark storefront glass, warm restaurant lights, blurred taxis','mixed warm storefront light and cool streetlight reflections, wet pavement glow, cinematic black gold and city-blue grade'],
['Convertible night drive','bold-nightlife','wearing a fitted black ribbed long-sleeve mini dress, sheer black tights, black heeled ankle boots, gold necklace, sleek city styling','beside a parked black convertible on a quiet overlook road at night with city lights below, dark leather interior, chrome reflections','cool city-light ambience mixed with warm dashboard glow, realistic reflections, sharp focus, low contrast cinematic night grade'],
['Cafe patio sundress','fresh-lifestyle','wearing a fitted black-and-cream floral sundress with thin straps, softly cinched waist, above-knee hem, gold necklace, leather sandals','at a quiet European-style cafe patio with marble tables, black bentwood chairs, potted flowers, cream awning, cobblestone street','soft late-afternoon cafe light, warm natural shadows, subtle grain, cream green and black lifestyle grade'],
['Tennis club whites','fresh-lifestyle','wearing a fitted white tennis dress with pleated mini skirt, slim straps, white ankle socks, clean white sneakers, gold studs','on a private tennis club court with deep green fencing, clay-toned surface, white benches, towel, water bottle, manicured hedges','bright late-afternoon sun with soft athletic shadows, crisp focus, clean green white and gold summer grade'],
['Ski lodge fireplace','soft-seductive','wearing a fitted cream off-shoulder cable-knit sweater dress with long sleeves, bare legs, wool socks, delicate gold necklace','inside a luxury ski lodge suite with stone fireplace, warm wood beams, cream faux-fur throw, leather armchair, snowy window view','warm fireplace glow mixed with soft lamp light, deep cozy shadows, subtle grain, amber cream and wood-toned winter grade'],
['Bookstore knit dress','candid-lifestyle','wearing a fitted chocolate brown long-sleeve knit mini dress, sheer black tights, black loafers, delicate gold necklace, soft intellectual styling','in a quiet boutique bookstore corner with tall wood shelves, stacked art books, leather reading chair, small brass lamp, warm neutral walls','soft reading-lamp light mixed with gentle window light, sharp focus, calm brown cream and gold grade'],
['Art gallery black dress','fashion-editorial','wearing a minimal fitted black sleeveless midi dress with square neckline, sculpted waist, black strappy heels, small gold earrings','in a modern art gallery after hours with white walls, polished concrete floor, large abstract canvases, slim black benches, quiet negative space','clean gallery track lighting with soft directional highlights, sharp focus, subtle grain, neutral white black and warm-gold grade'],
['Desert villa linen','fresh-lifestyle','wearing a fitted sand-colored linen mini dress with deep square neckline, thin straps, sculpted waist, gold jewelry, tan strappy sandals','on a private desert villa patio with pale stucco walls, arched doorway, terracotta pots, low cream seating, distant dry hills','warm desert sunset light, soft side shadows, golden rim light, sand cream and gold grade'],
['Marina navy dress','summer-sultry','wearing a fitted navy linen mini dress with deep square neckline, thin straps, sculpted waist, gold necklace, tan strappy sandals','on a quiet marina boardwalk with white boats, teak docks, chrome railings, blue water, cream canvas awnings, upscale nautical atmosphere','bright late-afternoon marina light, clean blue-and-white reflections, sharp focus, crisp coastal lifestyle grade'],
['Pool cabana bikini','summer-sultry','wearing a tasteful black triangle bikini under an open oversized cream crochet cover-up, gold body chain, small hoops, barefoot resort styling','inside a private pool cabana with cream curtains, rattan loungers, folded towels, blue pool reflections, potted palms, pale stone floor','soft poolside shade with bright sun reflections, flattering indirect light, sharp focus, clean resort color grade'],
['Beach boardwalk coral','summer-sultry','wearing a fitted coral ribbed knit mini dress with thin straps, sculpted waist, gold jewelry, tan sandals, relaxed seductive summer styling','on a quiet wooden beach boardwalk with dunes, sea grass, distant ocean, warm sky, simple railing, coastal sunset atmosphere','golden sunset backlight with warm side fill, soft rim light, peach gold and sand color grade'],
['White resort stairs','summer-sultry','wearing a fitted white halter mini dress with open-back detail, sculpted waist, gold earrings, nude strappy heels, resort evening styling','on whitewashed resort stairs with bougainvillea, cream stucco walls, terracotta pots, pale stone steps, Mediterranean vacation atmosphere','warm late-afternoon sun with soft wall bounce, realistic shadows, white pink and gold grade'],
['Tropical veranda set','fresh-lifestyle','wearing a fitted sage green linen two-piece set with cropped square-neck top and high-waisted tailored shorts, gold jewelry, tan sandals','on a shaded tropical veranda with dark wood deck, cream cushions, large palms, rattan chair, open-air resort architecture','soft tropical shade with warm sun filtering through palms, dappled shadows, green cream and tan grade'],
['Italian alley sundress','fresh-lifestyle','wearing a fitted black square-neck sundress with thin straps, above-knee hem, small gold hoops, leather sandals, travel styling','on a quiet old-town stone alley with cream walls, shuttered windows, potted plants, small cafe table, cobblestone path','soft late-afternoon street light bounced from pale walls, warm stone and cream grade'],
['Museum steps strapless','fashion-editorial','wearing a fitted black strapless midi dress with sculpted bodice, black slingback heels, minimal gold earrings, sleek editorial styling','on wide pale stone museum steps with tall columns, clean architecture, minimal city background, refined cultural daytime atmosphere','clean soft daylight with gentle architectural shadows, neutral stone black and gold grade'],
['Red gallery satin','fashion-editorial','wearing a fitted deep red satin midi dress with square neckline, thin straps, sculpted waist, black strappy heels, gold earrings','inside a contemporary art gallery with white walls, polished concrete floor, large abstract painting, slim bench, quiet negative space','soft gallery track lighting with warm highlights, deep red white and black grade'],
['Boutique fitting room','fashion-editorial','wearing a fitted black corset-style top with high-waisted wide-leg cream trousers, black pointed heels, gold necklace, sleek boutique styling','inside an upscale boutique fitting room with full-length mirror, warm wood panels, brass clothing rack, neutral curtains, soft carpet','warm flattering fitting-room mirror light, soft even glow, sharp fabric detail, cream black and brass grade'],
['Runway backstage','fashion-editorial','wearing a fitted charcoal strapless mini dress with sheer black tights, black pointed heels, slick gold earrings, confident backstage styling','in a fashion-show backstage corner with garment racks, black curtains, makeup table lights, folding chairs, organized creative clutter','warm makeup bulbs mixed with soft overhead backstage light, realistic shadows, black charcoal and amber grade'],
['Hotel bar emerald velvet','bold-nightlife','wearing a fitted emerald velvet mini dress with long sleeves, deep square neckline, sheer black tights, black stilettos, gold hoops','inside an upscale hotel bar with dark wood counter, black marble, brass shelves, amber bottles, velvet stools, refined nightlife atmosphere','low amber bar lighting with reflective highlights, deep shadows, emerald black and gold cinematic grade'],
['Neon arcade leather','bold-nightlife','wearing a fitted black cropped tank with high-waisted black leather mini skirt, sheer black tights, black boots, silver hoops, playful nightlife styling','inside a moody retro arcade lounge with neon signs, dark walls, glowing game cabinets, glossy floor reflections','magenta and cyan neon light mixed with soft face fill, sharp focus, cinematic night color contrast'],
['Speakeasy booth','bold-nightlife','wearing a fitted black lace-sleeve mini dress with opaque lining, sheer black tights, black heels, delicate gold jewelry','in a private speakeasy booth with deep red velvet seating, dark wallpaper, small round table, candle glow, brass lamp','low candle and brass-lamp light, soft face highlights, deep warm shadows, red black and gold grade'],
['Silver club hallway','bold-nightlife','wearing a fitted silver satin mini dress with thin straps, black strappy heels, small studs, sleek party-night styling','in an upscale club hallway with dark mirrored walls, soft LED strips, black carpet, metallic reflections, private nightlife atmosphere','cool silver-blue hallway light with warm skin-tone fill, glossy reflections, cinematic club color grade'],
['Sunday bed sweater','soft-seductive','wearing an oversized oatmeal off-shoulder knit sweater with fitted cream sleep shorts barely visible, bare legs, delicate gold necklace','in a soft neutral bedroom with white linen bedding, walnut nightstand, cream curtains, ceramic mug, folded throw blanket','soft diffused morning window light, gentle warm shadows, cream beige and wood color grade'],
['Record player apartment','soft-seductive','wearing a fitted black ribbed tank dress with low square neckline, bare legs, small gold hoops, delicate necklace, relaxed apartment styling','in a cozy music-corner apartment with walnut record console, vinyl sleeves, soft sofa, warm lamp, cream wall, textured rug','warm lamp glow with soft side shadows, cozy amber brown and cream color grade'],
['Cabin window knit','soft-seductive','wearing a fitted chocolate brown off-shoulder knit mini dress with long sleeves, wool socks, delicate gold necklace, cozy winter styling','inside a modern cabin beside a snowy window with wood walls, cream boucle chair, wool blanket, stone fireplace in background','soft overcast window light mixed with fireplace glow, cozy brown cream and snow-blue grade'],
['Coffee counter casual','candid-lifestyle','wearing a fitted white ribbed tank top tucked into high-waisted black lounge shorts, delicate gold necklace, bare legs, relaxed morning styling','in a bright modern kitchen by a stone coffee counter with walnut cabinets, cream backsplash, espresso machine, ceramic mug','soft morning kitchen light, gentle realistic shadows, cream white and warm wood grade'],
['Flower market jeans','candid-lifestyle','wearing a fitted black long-sleeve top with high-waisted straight-leg blue jeans, black belt, small gold hoops, casual flattering city styling','inside a small upscale flower-and-grocery market with buckets of flowers, wood crates, soft produce colors, cream tile floor','soft natural storefront window light, gentle shadows, realistic colorful lifestyle grade'],
['Laundry room leggings','candid-lifestyle','wearing a fitted grey cropped long-sleeve top with high-waisted black leggings, white ankle socks, minimal gold studs, casual at-home styling','in a clean upscale apartment laundry room with cream cabinets, stacked machines, folded towels, woven basket, warm neutral walls','soft overhead utility light mixed with warm window fill, clean neutral color grade'],
['Pilates studio mocha','fitness-lifestyle','wearing a fitted mocha matching pilates set with square-neck crop top and high-waisted leggings, white grip socks, tiny gold studs','inside a boutique pilates studio with reformer machines, pale wood floors, cream walls, large mirror, folded towels','soft clean studio daylight, gentle mirror reflections, cream mocha and pale wood grade'],
['Running track sunset','fitness-lifestyle','wearing a fitted black athletic crop top with high-waisted biker shorts, white running shoes, minimal gold studs, sleek athletic styling','on a quiet outdoor running track at sunset with red lanes, empty bleachers, distant trees, water bottle nearby','warm sunset side light, crisp athletic shadows, red gold and black grade'],
['Yoga terrace sage','fitness-lifestyle','wearing a fitted sage green matching yoga set with square-neck sports bra and high-waisted leggings, bare feet, small gold studs','on a private rooftop yoga terrace with wood decking, rolled mat, potted greenery, low cream seating, soft city skyline','soft sunrise light with gentle warm highlights, sage cream and gold grade'],
['Country stable denim','fresh-lifestyle','wearing a fitted white ribbed tank tucked into high-waisted dark denim shorts, brown leather belt, gold hoops, brown riding boots','outside a clean luxury horse stable with dark wood doors, pale gravel path, white fencing, green paddock, leather tack details','warm late-afternoon country light, soft natural shadows, green white and brown grade']
];

const sections = [
  { key: 'wardrobe', title: 'Wardrobe fallback / manual lock', paste: 'Paste into WARDROBE fallback/manual lock' },
  { key: 'environment', title: 'Environment fallback / manual lock', paste: 'Paste into ENVIRONMENT fallback/manual lock' },
  { key: 'lighting', title: 'Lighting/style fallback / manual lock', paste: 'Paste into LIGHTING/STYLE fallback/manual lock' },
  { key: 'brief', title: 'User creative brief', paste: 'Paste into USER CREATIVE BRIEF' },
  { key: 'gaze', title: 'Gaze / expression bias', paste: 'Paste into GAZE / EXPRESSION BIAS' },
  { key: 'rear', title: 'Rear / side bias · Shot 3', paste: 'Paste into REAR / SIDE BIAS · SHOT 3' },
  { key: 'variety', title: 'Pose variety / anti-repetition', paste: 'Paste into POSE VARIETY / ANTI-REPETITION' }
];

const vibes = {
  'seductive-luxury': 'seductive upscale lifestyle shoot, fitted evening outfit, confident eye contact, varied flattering poses, tasteful sensuality, realistic influencer photo',
  'summer-sultry': 'sun-warmed sultry summer lifestyle shoot, tasteful fitted resort styling, confident eye contact, relaxed vacation energy, varied flattering poses, realistic influencer photo',
  'bold-nightlife': 'bold evening nightlife lifestyle shoot, sleek fitted outfit, magnetic eye contact, refined sultry confidence, varied camera angles, realistic premium social-media photo',
  'soft-seductive': 'soft seductive intimate lifestyle shoot, cozy fitted styling, warm expressive eyes, natural half-smile, varied flattering poses, realistic candid influencer photo',
  'fashion-editorial': 'fashion-forward editorial lifestyle shoot, garment readability prioritized, fitted styling, confident direct gaze, clean intentional compositions, realistic influencer photo',
  'candid-lifestyle': 'candid lifestyle shoot, unposed in-between moments, fitted styling, playful expression, direct connection with camera, realistic social-media photo',
  'fitness-lifestyle': 'premium fitness lifestyle shoot, fitted athletic styling, confident eye contact, sculpted but natural movement, clean realistic social-media photo',
  'fresh-lifestyle': 'fresh upscale daytime lifestyle shoot, fitted summer styling, natural confident expression, soft realistic light, varied flattering poses, realistic influencer photo'
};

const defaults = { locks: { wardrobe:false, environment:false, lighting:false, brief:false, gaze:false, rear:false, variety:false }, selected: {}, logicMode: 'pack', vibe: 'seductive-luxury', keepConsistency: true, antiCollage: true, customPacks: [] };
let state = loadState();
let packs = [...packRows.map(row => ({name:row[0], vibe:row[1], wardrobe:row[2], environment:row[3], lighting:row[4], tags: row[0].toLowerCase().split(/\s+/)})), ...(state.customPacks || [])];

function loadState(){ try { return {...defaults, ...(JSON.parse(localStorage.getItem(STORAGE_KEY))||{})}; } catch { return structuredClone(defaults); } }
function save(){ state.customPacks = packs.filter(p=>p.custom); localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); toast('Saved'); }
const pick = arr => arr[Math.floor(Math.random()*arr.length)];
const byVibe = v => packs.filter(p => p.vibe === v || (p.tags||[]).includes(v));
function augment(key, text){ let t=(text||'').trim(); if(state.keepConsistency){ if(key==='wardrobe'&&!/same outfit/i.test(t)) t+=', same outfit throughout the photoshoot'; if(key==='environment'&&!/same location/i.test(t)) t+=', same location throughout the photoshoot'; if(key==='lighting'&&!/same lighting|consistent lighting/i.test(t)) t+=', same lighting direction and color grade throughout the photoshoot'; } return t; }
function guidance(){ return { brief: vibes[state.vibe] || vibes['seductive-luxury'], gaze: 'confident engaging presence, direct eye contact with the camera, eyes near the lens, warm magnetic connection, varied expressions including soft smile, playful half-smile, subtle smirk, relaxed laugh, calm closed-mouth smile, and inviting serious gaze', rear: 'favor a mix of full-body angles: side view, three-quarter rear, over-the-shoulder body orientation, walking-away-with-face-turned-back, and seated side angle; keep her face visible and eye contact alive even when her body faces away', variety: 'prioritize full-body and three-quarter-body compositions before waist-up crops; vary camera distance, low angle, eye-level angle, slight high angle, body orientation, crop, hand placement, gaze, and expression between photos; include at least one full-body outfit read and one wider environmental shot; no repeated pose or composition' }; }
function composeFromPack(pack){ return { wardrobe:augment('wardrobe',pack.wardrobe), environment:augment('environment',pack.environment), lighting:augment('lighting',pack.lighting), ...guidance() }; }
function pool(){ const p=byVibe(state.vibe); return p.length>=4 ? p : packs; }
function smartPack(){ return pick(pool()); }
function randomIndependent(){ return { wardrobe:augment('wardrobe',pick(packs).wardrobe), environment:augment('environment',pick(packs).environment), lighting:augment('lighting',pick(packs).lighting), ...guidance() }; }
function sectionValue(key){ if(['brief','gaze','rear','variety'].includes(key)) return guidance()[key]; return augment(key, pick(state.logicMode==='independent' ? packs : pool())[key]); }
function randomizeSection(key){ state.selected[key] = sectionValue(key); render(); }
function randomize(all=false){ const generated = state.logicMode==='independent' ? randomIndependent() : composeFromPack(smartPack()); for(const s of sections){ if(all || !state.locks[s.key]) state.selected[s.key]=generated[s.key]; } render(); }
function render(){
  document.getElementById('logicMode').value=state.logicMode; document.getElementById('keepConsistency').checked=state.keepConsistency; document.getElementById('antiCollage').checked=state.antiCollage;
  const vibeSelect=document.getElementById('vibeSelect'); vibeSelect.innerHTML=Object.entries(vibes).map(([k])=>`<option value="${k}">${label(k)} (${byVibe(k).length || packs.length})</option>`).join(''); vibeSelect.value=state.vibe;
  const root=document.getElementById('sectionCards'); root.innerHTML='';
  for(const s of sections){ const card=document.createElement('article'); card.className=`card ${state.locks[s.key]?'locked':''}`; card.innerHTML=`<div class="card-head"><div><h3>${s.title}</h3><p class="sub">${s.paste}</p></div><div class="lockline"><label><input type="checkbox" data-lock="${s.key}" ${state.locks[s.key]?'checked':''}/> Lock</label></div></div><textarea class="prompt" data-key="${s.key}">${state.selected[s.key]||''}</textarea><div class="card-actions"><button class="small" data-random="${s.key}">Randomize this</button><button class="small secondary" data-copy="${s.key}">Copy</button></div>`; root.appendChild(card); }
  document.querySelectorAll('[data-lock]').forEach(el=>el.onchange=e=>{state.locks[e.target.dataset.lock]=e.target.checked; render();});
  document.querySelectorAll('[data-key]').forEach(el=>el.oninput=e=>{state.selected[e.target.dataset.key]=e.target.value; updateCombined();});
  document.querySelectorAll('[data-random]').forEach(el=>el.onclick=e=>randomizeSection(e.target.dataset.random));
  document.querySelectorAll('[data-copy]').forEach(el=>el.onclick=e=>copy(state.selected[e.target.dataset.copy]||''));
  updateCombined();
}
function updateCombined(){ let block=sections.map(s=>`${s.title}\n${state.selected[s.key]||''}`).join('\n\n---\n\n'); if(state.antiCollage) block+='\n\n---\n\nNegative add-on\ncollage, photo collage, contact sheet, grid layout, split screen, multiple photos in one image, multiple panels, duplicate woman, repeated subject, multiple copies of the same woman, storyboard, four images, multiple frames, blank expression, looking away in every shot, tight waist-up crop in every image, cropped legs, hidden full outfit'; document.getElementById('combinedOutput').textContent=block; }
function label(k){return k.split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');} function toast(msg){const t=document.getElementById('toast'); t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),1300);} async function copy(txt){await navigator.clipboard.writeText(txt); toast('Copied');}

document.getElementById('randomizeAll').onclick=()=>randomize(false); document.getElementById('copyAll').onclick=()=>copy(document.getElementById('combinedOutput').textContent); document.getElementById('copyCombined').onclick=()=>copy(document.getElementById('combinedOutput').textContent); document.getElementById('saveState').onclick=save; document.getElementById('logicMode').onchange=e=>{state.logicMode=e.target.value; randomize(false);}; document.getElementById('vibeSelect').onchange=e=>{state.vibe=e.target.value; randomize(false);}; document.getElementById('keepConsistency').onchange=e=>{state.keepConsistency=e.target.checked; randomize(false);}; document.getElementById('antiCollage').onchange=e=>{state.antiCollage=e.target.checked; updateCombined();};
document.getElementById('addPack').onclick=()=>{ const p={ name:newPackName.value||'Custom style set', wardrobe:newWardrobe.value, environment:newEnvironment.value, lighting:newLighting.value, tags:newNotes.value.split(',').map(x=>x.trim()).filter(Boolean), vibe:state.vibe, custom:true }; if(!p.wardrobe||!p.environment||!p.lighting){toast('Fill wardrobe, environment, lighting'); return;} packs.push(p); save(); newPackName.value=newWardrobe.value=newEnvironment.value=newLighting.value=newNotes.value=''; randomize(false); };
if(!Object.keys(state.selected||{}).length) randomize(true); else render();
